# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76aba88beb95d1865c2eca0f17c4fd66d59e21fa9c4411200faffadb22fccbc697d912a04b38cb50514b28dc01b7484c76f0118803e27b54cd6af4f733c373f4

test:
  secret_key_base: e4a2ad1bffed5f10e9d412e2273183595f04a9d19add56d13b7daacc897184ea419ed6da9bc55fe394d22366b7b769c9cab018f2b7740c4d472ccf4f945b38f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
